Connecting with an API
robinbenitezmora/bookstore pull request #4
Opened 2022-09-22 18:40 UTC by robinbenitezmora

As a part of Microverse practice, this time we are sharing with our app the data by means an API in order to go over the concepts inititalized in former challenges.

2022-09-22 19:02 UTC, vickymarz requested changes
Hi @robinbenitezmora, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️

- [ ] Kindly remove all unused commented code from your codebase to make your code clean and readable 👍🏽 

- [ ] According to the project requirement, kindly use [createAsyncThunk](https://redux-toolkit.js.org/api/createAsyncThunk) for making API calls 👍🏽 

- [ ] .

_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-22 19:02 UTC, victorokoroji commented on src/redux/books/books.js
> +};
- [ ] According to the project requirement, kindly use [createAsyncThunk](https://redux-toolkit.js.org/api/createAsyncThunk) for making API calls 👍🏽 .

2022-09-22 19:02 UTC, victorokoroji commented on src/redux/books/books.js
> +  // });
- [ ] Kindly remove all unused commented code from your codebase to make your code clean and readable 👍🏽

2022-09-22 21:42 UTC, robinbenitezmora commented on src/redux/books/books.js
> +};
Hello @vickymarz , could you give a 'thunk' example in order to apply it. Thanks a lot

2022-09-22 22:09 UTC, vickymarz commented on src/redux/books/books.js
> +};
I think you should check out for createAsynctThunk in your microverse resource / learning materials or you check it online on redux toolkit dicumentation

2022-09-23 03:55 UTC, Davidosky007 requested changes
Hi @robinbenitezmora 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* createAsyncThunk used for creating thunk action creators 👍 
* Connect an existing API via Redux 👍 
* Good looking readme file 👍 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidosky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 03:55 UTC, Davidosky007 commented on src/components/library/Book-list.js
> +    dispatch(getBooks());
* Good job using createAsyncThunk for your API calls but you have a new bug 🐛 now as when i create a book it doesn't show up on the page, kindly fix this error 🙏 
![image](https://user-images.githubusercontent.com/52497246/191889395-f171868a-e9ba-4c3b-b408-6c036419a9a8.png)

2022-09-23 13:39 UTC, mahbubul14 approved these changes
# Project Approved :trophy: :tada: 

Hi @robinbenitezmora , 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linter error.
:heavy_check_mark: Descriptive readme file.
:heavy_check_mark: Well implemented suggested changes.

### Optional suggestions :arrow_down_small: 

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

- [ ] The commit message should be written in the imperative tense and the first letter should also be capitalized. `Ex: "Fix bug" instead of "Fixed bug".` [For more details...](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-09-23 13:45 UTC, merged